create table users(
                      id int primary key generated by default as identity,
                      email varchar(20) not null,
                      password varchar(20) not null,
                      registrationDate DATE
);
insert into users (email, password, registrationDate) VALUES
('i@bikmeev.ru','123', '2022-11-12 '),
('a@bikmeev.ru','456', '2020-07-26 ');

